# Generated by Django 5.1.3 on 2024-12-05 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exercicios", "0001_initial"),
        ("planos_de_treino", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExercicioDoPlano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repeticoes", models.PositiveIntegerField()),
                ("series", models.PositiveIntegerField()),
                ("peso", models.FloatField(blank=True, null=True)),
                (
                    "exercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planos_inclusivos",
                        to="exercicios.exercicio",
                    ),
                ),
                (
                    "plano_de_treino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercicios_do_plano",
                        to="planos_de_treino.planodetreino",
                    ),
                ),
            ],
        ),
    ]
