# Generated by Django 5.1.3 on 2024-12-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercicios_dos_planos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exerciciodoplano",
            old_name="peso",
            new_name="carga",
        ),
        migrations.AddField(
            model_name="exerciciodoplano",
            name="numero_equipamento",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
