# Generated by Django 5.1.3 on 2024-12-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercicios_dos_planos", "0002_rename_peso_exerciciodoplano_carga_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exerciciodoplano",
            name="carga",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exerciciodoplano",
            name="series",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
