# Generated by Django 5.1.3 on 2024-12-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercicios", "0001_initial"),
        ("exercicios_dos_planos", "0001_initial"),
        ("planos_de_treino", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="planodetreino",
            name="exercicios",
            field=models.ManyToManyField(
                related_name="planos_de_treino",
                through="exercicios_dos_planos.ExercicioDoPlano",
                to="exercicios.exercicio",
            ),
        ),
    ]
